env:
  es6: true
  browser: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
plugins:
  - react
  - prettier
rules:
  prettier/prettier: error
  react/prop-types: warn
  no-unused-vars: error
  no-undef: error
extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
