image: paciolanhub/alpine-node-dev:10.4.1

variables:
  LIB: my-component
  REPO_URL: gitlabdev.paciolan.info

stages:
  - build

Build & Test:
  stage: build
  tags:
    - gitlabdev
  except:
    - tags
  before_script:
    # npm user authentication
    - printf %"s\n" //registry.npmjs.org/:_authToken=$NPM_TOKEN email=$NPM_EMAIL > ~/.npmrc

    # npm install
    - npm install npm -g
    - npm ci
  script:
    - npm run build
    - npm run lint
    - npm run test:coverage -- --colors
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/
      - node_modules/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
